### ISSUE TITLE
NameError in demo.py

### ISSUE THREAD

**Issue by Not-Nik** [AliaksandrSiarohin/first-order-model#62] opened 2020-04-01 08:02 UTC
Hey there,
I just tried to test out demo.py and with the command:
`python3 demo.py --config config/bair-256.yaml --driving_video crop.mp4 --source_image sup-mat/foto.png --checkpoint bair-cpk.pth.tar --relative --adapt_scale`
I get the following output:
```
/usr/local/lib/python3.7/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/usr/local/lib/python3.7/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
  0%|                                                                             | 0/229 [00:00<?, ?it/s]/usr/local/lib/python3.7/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/usr/local/lib/python3.7/site-packages/torch/nn/functional.py:1332: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
100%|███████████████████████████████████████████████████████████████████| 229/229 [10:21<00:00,  2.71s/it] 
Traceback (most recent call last):
  File "demo.py", line 134, in <module>
    imageio.mimsave(opt.result_video, [img_as_ubyte(frame) for frame in predictions], fps=fps)
  File "demo.py", line 134, in <listcomp>
    imageio.mimsave(opt.result_video, [img_as_ubyte(frame) for frame in predictions], fps=fps)
NameError: name 'img_as_ubyte' is not defined
```
Any idea what could cause this?

**Comment by AliaksandrSiarohin** [comment] 2020-04-01 08:39
The problem is missing import, fixed now.

**Closed as completed by AliaksandrSiarohin** 2020-04-01 08:39 UTC
